### ISSUE TITLE
RTCView Not Displaying Video on iOS 13.0 simulators 

### ISSUE THREAD

**Issue by Ingibjorg** [react-native-webrtc/react-native-webrtc#701]
#### Expected behavior
Video should be displayed in RTCView on iPhone 11 Pro Max - iOS 13.0 simulator.

#### Observerd behavior
Video data seems to be sending over the peer connection but the video is not displayed in the RTCView. The RTCView displays a red view instead.

#### Steps to reproduce the problem
Upgrade to the latest Xcode version 11.0 and attempt to broadcast a video on the latest iPhone 11 Pro Max - iOS 13.0 simulator.

#### Platform information

* **React Native version**: 0.60.4
* **Plugin version**: 1.75.0
* **OS**:  iOS
* **OS version**: 13.0
* **Xcode version**: 11.0

**Comment by saghul** [comment]
This got fixed with the M75 upgrade. I'm. not sure why you're still having the problem. Do you see any errors?/

**Comment by pratnikau** [comment]
Same issue. RTCView doesn't render anything, I've tried on a 1.67.0 and 1.75.0 versions.
@Ingibjorg Did you manage to fix this issue?

React Native version: 0.59.10
Plugin version: 1.67.0
OS: iOS
OS version: 13.0
Xcode version: 11.0

**Comment by saghul** [comment]
Do you see any errors in the Xcode console?

**Comment by Ingibjorg** [comment]
@saghul it looks like this issue only happens on iOS 13 simulators.

Here's the logs from Xcode:

```
2019-09-25 11:01:34.597 [info][tid:com.facebook.react.WebSocketModuleQueue][RCTSRWebSocket.m:516] SocketRocket: In debug mode.  Allowing connection to any root cert
2019-09-25 11:01:34.596742-0700 MyApp[12124:15366273] SocketRocket: In debug mode.  Allowing connection to any root cert
2019-09-25 11:01:34.931 [info][tid:com.facebook.react.WebSocketModuleQueue][RCTSRWebSocket.m:516] SocketRocket: In debug mode.  Allowing connection to any root cert
2019-09-25 11:01:34.931387-0700 MyApp[12124:15366277] SocketRocket: In debug mode.  Allowing connection to any root cert
2019-09-25 11:01:35.292 [tid:signaling_thread 0x0x7fe93a654250][WebRTCModule+VideoTrackAdapter.m:162] [VideoTrackAdapter] Adapter created for track video12791
2019-09-25 11:01:35.291995-0700 MyApp[12124:15356971] [VideoTrackAdapter] Adapter created for track video12791
```

**Comment by saghul** [comment]
Local video or remote video?

**Comment by pratnikau** [comment]
Still can't make RTCView work on iOS13 device. Just a black screen and error in console log

No video stream for react tag: d5a118c9-b13e-474c-bb1c-9e00341ffe57

React Native version: 0.60.5 
Plugin version: 1.75.0
OS: iOS
OS version: 13.0
Xcode version: 11.0

**Comment by saghul** [comment]
> No video stream for react tag: d5a118c9-b13e-474c-bb1c-9e00341ffe57

This means the streamURL is not recognized by the plugin, Where did you take it from? Do you have a small code snippet which shows how you attach to the stream? Is it a local or a remote one?

**Comment by pratnikau** [comment]
It's a remote one. Local stream runs ok. I'll try to figure out where the problem can be or give you a minimal reproducible code snippet.

iOS12 with react-native-webrtc 1.67.0 is fine and iOS13 has a black-screen.
After upgrading to 1.75.0 black screen appears even on iOS12 devices.

**Comment by saghul** [comment]
There were major changes to the API in 1.69: https://github.com/react-native-webrtc/react-native-webrtc/releases/tag/1.69.0 Have you adapted your code already?

**Comment by Ingibjorg** [comment]
@saghul it's remote video. I never had version 1.69 only 1.75. The video works fine on iOS 12 devices and simulators so @pratnikau is not experiencing the same issue reported here.

**Comment by manhquyen** [comment]
when i use xcode 10 build local video works fine but use xcode 11 build local video just a black screen on devices iOS 13

**Comment by stwiname** [comment]
We found that there is a problem with the metal renderer on iOS 13. Forcing usage of the OpenGL renderer solved it for us

**Comment by saghul** [comment]
Good find! Are you having problems when running on device?

I can make it use GL for simulators and Metal otherwise but given that a camera can not be emulated their usefulness is already not that good...

**Comment by stwiname** [comment]
Yes, we had problems on devices too. We're now using OpenGL for all iOS 13. 

I believe it has been fixed in WebRTC now, but can't find where I found that out

**Comment by saghul** [comment]
We haven’t seen problems on device, but this is good to know, thanks!

If you can find a reference in a WebRTC bug or commit that would be helpful. Thanks!

**Comment by felippepuhle** [comment]
Same here. Tried a lot of things, but all I got is a black screen (even on real devices).

How can we solve this?

Thanks!

**Comment by sesm** [comment]
I've observed red screen on iOS simulator too.
Noticed the following: red screen is only visible with `H264` codec when `packetLoss` reported by WebRTC `getStats` is high. When we force `VP8` codec red screen is never seen. Also, red screen is not reproducible on real device, even with `H264` and high `packetLoss`. 
I suspect that that's a bug with `H264` decoder, which is not reproducible on real device because of a different decoder implementation (possibly a hardware implementation)

**Comment by saghul** [comment]
@sesm Makes sense.

**Comment by sachalegrand** [comment]
@stwiname is correct, this has to do with the Metal Renderer.

However, it took me a little while to figure out how to "force using OpenGL". I could not find an option in Info.plist or any other project setting. Would be interested to know if that is possible instead of this hacky patch.
In the end what I did is patch the file ./ios/RCTWebRTC/RTCVideoViewManager.m

On line 128 you got 
```
#if defined(RTC_SUPPORTS_METAL)
    RTCMTLVideoView *subview = [[RTCMTLVideoView alloc] initWithFrame:CGRectZero];
    subview.delegate = self;
    _videoView = subview;
#else
    RTCEAGLVideoView *subview = [[RTCEAGLVideoView alloc] initWithFrame:CGRectZero];
    subview.delegate = self;
    _videoView = subview;
#endif 
``` 

change it to only

```
    RTCEAGLVideoView *subview = [[RTCEAGLVideoView alloc] initWithFrame:CGRectZero];
    subview.delegate = self;
    _videoView = subview;
```

I did read that is fixed in 1.75 though, however I did not have the time to update my whole project and so this fix seems to be working ok with 1.69.2.

**Comment by saghul** [comment]
FTR I do see the video correctly on the simulator. I wonder if iOS 13.2.2 fixed things...

**Comment by Ingibjorg** [comment]
@saghul the video is still not showing for me on iPhone 11 simulator - iOS 13.2.2

**Comment by saghul** [comment]
Hum. I'll give it a test, maybe we can switch to using the GL renderer on the simulators then.

**Comment by sesm** [comment]
@Ingibjorg are you seeing a red screen a black screen or something else?
@saghul I'll be happy to test the GL renderer fallback, in our project the issue is easily reproducible.

**Comment by saghul** [comment]
@sesm Sweet. See the file mentioned in https://github.com/react-native-webrtc/react-native-webrtc/issues/701#issuecomment-553225845 you need edit that ifdef and add and or for the simulator target. That should do.

**Comment by sesm** [comment]
@saghul just tested this solution, it didn't help in my case, I'm still seeing a red screen.
I've changed code to this:
```
- (instancetype)initWithFrame:(CGRect)frame {
  if (self = [super initWithFrame:frame]) {
    RTCEAGLVideoView *subview = [[RTCEAGLVideoView alloc] initWithFrame:CGRectZero];
    subview.delegate = self;
    _videoView = subview;

    RCTLogWarn(@"Init with RTCEAGLVideoView");

    _videoSize.height = 0;
    _videoSize.width = 0;

    self.opaque = NO;
    [self addSubview:self.videoView];
  }
  return self;
}
```
I can see `Init with RTCEAGLVideoView` in logs, but the screen is red.
<img width="1068" alt="Screenshot 2019-11-15 at 15 53 08" src="https://user-images.githubusercontent.com/1313744/68944906-1d9a7b00-07c0-11ea-970a-2d2e2a2db497.png">

**Comment by saghul** [comment]
Uh, then I have no idea...

**Comment by Ingibjorg** [comment]
@sesm I'm seeing a red screen.

**Comment by sesm** [comment]
@Ingibjorg could you please check what codec your incoming video stream is using? You can find it in `getStats` output (search for an entry with `mediaType: video` and `packetsReceived` and check the value of `googCodecName`) or just post `getStats` output here.
If your codec is `H264`, could you please try to force a different codec (by manipulating SDP offer/answer) and check if the red screen goes away?

**Comment by jakew009** [comment]
This appears to be the same bug:
https://bugs.chromium.org/p/webrtc/issues/detail?id=11012

**Comment by githupchenqiang** [comment]
I will project running in ios12 equipment can work normally, but when I will run to load ios13 equipment on the remote video and local video can't show, but video call each other can be acceptable to my video and audio

**Comment by githupchenqiang** [comment]
I will project running in ios12 equipment can work normally, but when I will run to load ios13 equipment on the remote video and local video can't show, but video call each other can be acceptable to my video and audio,I was in the xcode simulator iphone11pro ios13.2.2 run on is normal, but the ios13.1 video on your mobile phone can't display

**Comment by wumke** [comment]
I'm testing on real device with following versions:
- React Native version: 0.44.0
- Plugin version: 1.75.3
- OS: iOS
- OS version: 13.3
- Xcode version: 11.3.1

I get no video, not for local and not for remote stream. Audio seems to work fine.
Any news or things to try on this topic?

(I updated from plugin 1.69.0 which I used before and which worked with my app in the store for previous ios releases, but that stopped working... 99$ a year for breaking my app, thank you Apple! )

**Comment by saghul** [comment]
That RN version is ancient. Can you please update to 0.6X and give it another try?

**Comment by wumke** [comment]
Since it works with the hack I'm going to leave it like this for now... Have no time for this project at the moment.

**Comment by saghul** [comment]
Fair enough. I'm going to close this for now, since there doesn't seem to be anything actionable at the moment. Holler if we need to reopen.
